### ISSUE TITLE
XML docs not generating on Win 10 - fine on macOS

### ISSUE THREAD

**Issue by DanBennettDev** [Cycling74/min-devkit#116]
Tthe XML docs are no longer generating for this package  https://github.com/DanBennettDev/max_cpg n either of my win machines, though they generate from the same package on macOS.  I've tried to track this down - but can't see any reason why doc_update() wouldn't be called, and I don't see any errors. 

I allow externals to initialise on all platforms (docs look like they're generated at first runtime). I've tried running max as admin and that has no effect. No error messages reported to console.

**Comment by tap** [comment]
I'm doing the following on Windows 10 Home (version 1803) on the MINGW64 command line (MSYS terminal that is installed when I installed Git):

* `cd ~/Documents/Max\ 8/Packages`
* `git clone  https://github.com/DanBennettDev/max_cpg`
* `cd max_cpg`
* `mkdir build`
* `cd build`
* `cmake -G "Visual Studio 15 2017 Win64" ..` 
* `cmake --build .`

I take a look at the "max_cpg" folder. There is no docs folder in there.

Then I launch Max and create an instance of `cpg.network~`.

When I look in the "max_cpg" folder I now see a "docs" folder and inside of it a "cpg.network~.maxref.xml" file. So it seems to work here...

I wonder if it could be a permissions problem? Are you running as the admin user? Are you building to the user's Max packages folder?

**Comment by DanBennettDev** [comment]
Thanks Tim.
I wasn't re-pulling the package, and rebuilding - so just the last step of your bullets and loading the external in Max. That was not resulting in docs rebuild. That was consistent over a bunch of builds as I made changes.

However, I just deleted the docs and build folders, and built from "mkdir build" onwards and this did result in docs update with the XML files populated as I'd expect.

**Comment by tap** [comment]
Thanks for the update, Dan. It's unclear to me from this description if there is a bug or not in the reference generation/updating.

Is your belief that there is still a problem (either in the code or in the documentation)?
Or is it your belief that everything is working properly?

Thanks!

**Comment by tap** [comment]
Okay, good to hear! I'm comfortable with considering this issue closed unless it shows up again.
