### ISSUE TITLE
Throwing in constructor crash

### ISSUE THREAD

**Issue by louisHougi** [Cycling74/min-devkit#126]
Hey,
I'm experiencing crash when I throw in my object constructor. 
``` c++
MyObject(const atoms& args = {}) 
{
if (args.empty())
   error("MyObject expects arguments")
}
```
I guess this happens because it leads to a throw during the construction of the dummy_instance of MyObject.
Modifying: `dummy_instance = std::make_unique<min_class_type>(std::nothrow);` and providing the correct constructor is what I'm doing now.
Best,

**Comment by tap** [comment]
Thanks for reporting this @louisHougi !  And also for providing the fix.

I will try to incorporate this in the next set of revisions.

**Comment by tap** [comment]
Closing this ticket here since it it tracked in the linked ticket above.
