### ISSUE TITLE
Visual Studio 2019 does not start when bang [generate min.hello-world]

### ISSUE THREAD

**Issue by alfonso73** [Cycling74/min-devkit#134]
Hi all,
as the issue title says...Visual Studio 2019 does not start when bang [generate min.hello-world] in Max8 Compile Code tag of the help for min-devkit

**Comment by tap** [comment]
The Min-DevKit and API v0.5 is now updated to work with VS 2019.

Cheers!

**Comment by alfonso73** [comment]
Hi Tim, many thanks
