### ISSUE TITLE
Notein messages causes the min.phasor~ object to crash

### ISSUE THREAD

**Issue by 141592653** [Cycling74/min-devkit#139]
Hello ! 
So I have this very simple patch that crashes when I play a note on my key board. I think it happens with all objects generated by the min-devkit. This only happens using the notein object. 

Cheers ! 

[bug.txt](https://github.com/Cycling74/min-devkit/files/4124140/bug.txt)

**Comment by tap** [comment]
Thanks for this report. Now tracking this as a part of the incident linked above.
