### ISSUE TITLE
Can't edit attributes using the inspector

### ISSUE THREAD

**Issue by hgeddon** [Cycling74/min-devkit#140]
Editing attributes in the inspector doesn't work.
Any keypress after selecting the input field next to the attribute is immediately deleted or replaced with the value that was present before editing.
Attributes can be edited with an attrui or messages to the object, just not in the inspector.
Seems to be across all of the min example objects but for an example create a 'min.textslider' and try to edit the 'offset' 'label' or 'range' attributes from the inspector and see what I mean. "onoff" boxes do work. 
I am testing on a PC running latest version of Windows 10 pro, Max 8.1.1 and the most recent version of the min-devkit.

**Comment by tap** [comment]
This is fixed in the latest versions of Min on the master branch.
