### ISSUE TITLE
cmake does not generate solution files with Visual Studio 2019

### ISSUE THREAD

**Issue by mourendxu** [Cycling74/min-devkit#142]
Running the cmake commandline or the GUI result in the following warning messages and errors. It basically looks like instead of trying to build the solutions, cmake is actually trying to build the project.
I am on Win 10, Cmake 3.16.4, Visual Studio Community 2019

Here are the errors I get:

`
>cmake -G "Visual Studio 16 2019" -A Win64 ..
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error in CMakeLists.txt:
  Failed to run MSBuild command:

    d:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe

  to get the value of VCTargetsPath:

    Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Framework
    Copyright (C) Microsoft Corporation. All rights reserved.

    Build started 3/15/2020 10:06:17 PM.

**Comment by mourendxu** [comment]
The solution so far seems to generate it for Visual Studio 2015, then open it in 2019 and run the upgrade.

**Comment by tap** [comment]
I've updated the ReadMe with instructions for Visual Studio 2019. In VS2019, x64 is the default architecture.

I just tested with the updated instructions on Win 10, Cmake 3.16.4, Visual Studio Community 2019 and this worked as desired.

I'll close the issue, but if it continues to be problematic then please feel free to re-open it.

Thanks!

**Comment by mourendxu** [comment]
Awesome. Thank you.
