### ISSUE TITLE
min.dcblocker is missing

### ISSUE THREAD

**Issue by mourendxu** [Cycling74/min-devkit#143]
I think this might be another need to update documentation situation. As far as I can tell, there is no min.dcbloker object, nor is there a source code for it. However, I did find its test, which referenced dcblocker in the api. 

min.dcblocker is reference several times in the documentation.  

Thank you.

**Comment by tap** [comment]
Thanks. This was moved to another package that is in development, but the future of that package is now uncertain. 

Documentation should be updated at a minimum, but perhaps we should bring that object back here as well...

**Comment by nefastosaturo** [comment]
I was looking for dcblocker and xfade from the WhereToLook Audio section of the docs. I found the latter in some old commits and in the ease package of yours @tap : https://github.com/Cycling74/ease/tree/master/source/projects
