### ISSUE TITLE
Blue/Cold Inlet?

### ISSUE THREAD

**Issue by mourendxu** [Cycling74/min-devkit#146]
Hi, I looked around in the documentation and the code, but I can't seem to find something that tells me how to make a blue/cold inlet? 

I guess the behavior can be emulated at the code level, but I also wanted the UI to be consistent, so, the user know what to expect.

Lastly, how do I tell which data came in which inlet? Is there a built in member somewhere that holds this info?

Thank you.

**Comment by tap** [comment]
Hi,

Currently, there is no support for this in Min. I have opened a feature request @ Cycling74/min-api#139

I hope this helps!
Tim

**Comment by mourendxu** [comment]
Thank you, Tim!

Looking forward to the updates.

Da.

___
www.WeareSoHappy.net

**Comment by mourendxu** [comment]
Ah sorry, got a question, is there a way to tell which inlet a message came from? Or is that not supported at the moment? 

Thanks.

**Comment by mourendxu** [comment]
never mind. I found it. I traced it back to the MIN_FUNCTION definition. 

It's in a variable called inlet :D

**Comment by robtherich** [comment]
FR tracked here, closing out: Cycling74/min-api#139
