### ISSUE TITLE
Midi In in Max 4 Live causing strange behavior

### ISSUE THREAD

**Issue by mourendxu** [Cycling74/min-devkit#153]
Hi,

I ran into a strange, or I just don't understand the problem at hand, issue that I was hoping somebody could help me. 

I am trying to grab the velocity of a midi note from a midiin inside of Max 4 Live. I used zl.delace to split the pitch and velocity info from a midiparse. I then send the velocity info to a message box's left outlet with the following: "velocity $1". 

I then take the output of the message box and plug into the input of my external. Inside of my external, I am catching anything. However, when I do get a message, my args.size is 0. But if I do a deferlow, right before the my external, everything works properly.

I read through the threading article, but I don't remember seeing a description of this behavior. 

Any help would be greatly appreciated.

Thank you.

**Comment by tap** [comment]
Hi! This problem was very recently fixed (v0.5). What version of the Min-API are you using?

**Comment by mourendxu** [comment]
Ohh great. How do I check?

**Comment by mourendxu** [comment]
Sorry, I am pretty sure that I am not using 0.5. I will update to 0.5 and re-check.

For now, I will close this issue.
