### ISSUE TITLE
package-info.json.in file missing from distribution

### ISSUE THREAD

**Issue by mourendxu** [Cycling74/min-devkit#154]
Hi, 

I installed min-devkit via Package manager. I was wondering if there is a procedure for updating the min-devkit inside of a package that I have already been working on? Do I just copy over the min-api and min-lib from the updated min-devkit package?

Thank you.

**Comment by tap** [comment]
Great question. Yes, that works fine.

In addition to documenting this (where? FAQ?) I wonder if a script or widget would be useful?

**Comment by mourendxu** [comment]
Documentation or script would be great.

One question though, I see my project has a bunch of solutions already made. If I simply copy over those folders, do I need to run Cmake again for my entire project?

Thank you.

**Comment by mourendxu** [comment]
Actually, I think a better question is where can I inject my external header and library includes in the cmake file? 

This way, I don't have to do it by hand in Visual studio.

Thank you!

**Comment by mourendxu** [comment]
Just want to give you guys an update, I copied over the min-api, min-lib directories, the CMakeLists.txt and the package-info.json. I re-ran Cmake and everything is a-ok.

Thank you!

Though, one thing, in package-info.json, I noticed the min-devkit did not fill out my external info correctly. It looks like I will have to go back and modify it by hand. All the externals and help entries are still pointing to the min-devkit names.

**Comment by tap** [comment]
Glad to hear you found success. The `package-info.json` file is generated from when CMake is run from the `package-info.json.in` template which is where you should place your changes.

**Comment by mourendxu** [comment]
Where is this package-info.json.in? I can't seem to find it in the min-devkit or my project directory.

Thank you.

**Comment by tap** [comment]
I can confirm the bug: Min-DevKit is not shipping `package-info.json.in` but it should be!

Thanks for this report!
