### ISSUE TITLE
not opening folder automatically

### ISSUE THREAD

**Issue by omarcostahamido** [Cycling74/min-devkit#170]
using lastest version of min sdk package.

on Create a Package tab "A new Package with that name will be created in your Packages folder. The folder will be opened for you when it is done being created."
it does create the folder but it does not open it.

Mac osx catalina, latest max/msp.

**Comment by omarcostahamido** [comment]
in fact, I just realized on max console:
`min.project: A problem occurred trying to create the new package`

**Comment by omarcostahamido** [comment]
following #158 , I manually copied the scripts folder (so yes, this issue needs to be reopen). That made the project folder open after creating the object (which makes max hang for a while), but the error message when creating the project, as well as the no automatic folder opening, still persist.

**Comment by robtherich** [comment]
hi Omar, just a quick note on this. The previous maintainer of the min-devkit recently left the company and we are doing our best to maintain the project while we find other teammates to pick up the slack. In the meantime you might be better off utilizing the min cmake tools directly from the command line as described in this cycling74 forum post: https://cycling74.com/forums/xcode-not-launching/replies/1#reply-5f8efdd3aa78fa6220e6b783

**Comment by omarcostahamido** [comment]
oh no! I did not know about that.
Thank you for those instructions.
Hopefully you can find a way to have more active development on min-sdk very soon. 
This is just awesome, I'm relying on it for the new work I am doing right now.

**Comment by robtherich** [comment]
this issue should be fixed with the above commit. once we are able to run some tests we will push a new version to the package manager.

**Comment by omarcostahamido** [comment]
thank you!

**Comment by robtherich** [comment]
just dropping a quick note to say version 0.5.7 is now in the package manager that should fix various issues with the launcher patch not functioning as expected (including the issue reported here).
