### ISSUE TITLE
Max crashes when accessing args out of range

### ISSUE THREAD

**Issue by omarcostahamido** [Cycling74/min-devkit#172]
Title says it all.

Question:
I do understand it could be angry with me for trying to that, but is it possible not to crash max entirely?
For now I can check first if there are arguments before fetching its value but here is the thing:
my previous projects running 0.4.9 ran fine, this crash is new to 0.5.4. So, I wonder if there is something that changed for the worst in the mean time and if there is something that can be done about it.

Thank you!
O

**Comment by robtherich** [comment]
if I understand the report, you are crashing when traversing beyond the bounds of std::vector, so this is not really an issue with min and is expected behavior.

**Comment by omarcostahamido** [comment]
Ok, yes, thank you.
