### ISSUE TITLE
Question: retrieve Package path

### ISSUE THREAD

**Issue by omarcostahamido** [Cycling74/min-devkit#176]
Question: how can I retrieve the directory path of the max package?
I need to access some files that I include in this package folder directly from within an external.

**Comment by omarcostahamido** [comment]
ok, so I found this:
`path p { path("fileinmypackage.extension") };`
Not sure it is the most elegant way to do it.

**Comment by robtherich** [comment]
seems like a fantastic way to do it.

**Comment by omarcostahamido** [comment]
haha, thx @robtherich 
I guess this is good enough, then.

**Comment by jeremybernstein** [comment]
Also note that there's an undocumented path prefix called ... `Package:/`, so for instance, passing `Package:/Mira` to `absolutepath` or `conformpath` will result in `"HD:/Users/uname/Documents/Max 8/Packages/Mira"` on my machine. I am not a min-sdk expert, I don't know if you can pass this type of path into `path()`, but I thought I'd mention it.

**Comment by omarcostahamido** [comment]
@jeremybernstein thank you so much for this secret hint. This was just what I needed!
