### ISSUE TITLE
Question: about threading?

### ISSUE THREAD

**Issue by omarcostahamido** [Cycling74/min-devkit#177]
I have a process that takes some time, like several seconds, involving reading from a file.
How can I make it so that Max won't hang while waiting for the results?
I read the threading doc on the website, but I am still pretty much confused about this.

**Comment by omarcostahamido** [comment]
following the thread [here](https://cycling74.com/forums/min-devkit-and-threading-questions), on which there has been no interaction with other people so far either (lol), I was able to get it to work without freezing Max. The problem is that I need to use an extra object like `delay 0` of `pipe 0` in order for it to work. Things will always come out in the scheduler thread right now. But, if they come in on the main thread, it will still freeze Max for a while.

**Comment by robtherich** [comment]
answered on your forum thread. in general the dev forum is the best place to ask questions, as there is a wider audience and therefore better chance it will get answered. the issue tracker is primarily for bugs and feature requests (as a loose guide).

**Comment by omarcostahamido** [comment]
thank you @robtherich

**Comment by omarcostahamido** [comment]
thx for that reference again @robtherich 
I was able to fix it. Interestingly enough, the solution for my specific problem has to deal with a little bit of everything that I had tried before and some of the new things I learned.
