### ISSUE TITLE
How to help update documentation?

### ISSUE THREAD

**Issue by omarcostahamido** [Cycling74/min-devkit#178]
Is it [here](https://github.com/Cycling74/min-devkit/tree/gh-pages) or on the [min-api](https://github.com/Cycling74/min-api/tree/master/doc) repo?

I've made PR for both [api](https://github.com/Cycling74/min-api/pull/168) and [sdk](https://github.com/Cycling74/min-devkit/pulls), which are pending. I saw some new things now, but I don't want to keep creating PR to the wrong place, if I am doing it.

Thank you

**Comment by robtherich** [comment]
the gh-pages branch is automatically generated from the guides in the main branch, so the main branches are the appropriate place for your PRs. Many thanks for your previous submissions, we are slowly working our way towards getting these integrated.
