### ISSUE TITLE
min-devkit conflict warning in package manager

### ISSUE THREAD

**Issue by byulparan** [Cycling74/min-devkit#193]
<img width="722" alt="스크린샷 2021-09-07 오전 3 49 00" src="https://user-images.githubusercontent.com/459573/132253754-e814135e-ffc7-4a28-b243-b65d4a56463c.png">

currently I used min-devkit from github. 
package manager say "conflict found. use package manager version".  
but also package say "The package manager version of min-devkit is deprecated. 
please use the Github repository for future updates"

How to resolve it? I want remove conflict warning in package manager.

**Comment by isabelgk** [comment]
Hi @byulparan ,

I believe this error comes from a version mismatch between the current version number in the package manager versus the one in your locally installed package. 

One question first: I notice that your screenshot shows the local version is 1.0.0. Do you have a local `package-info.json` in your cloned copy of the min-devkit or is there just the `package-info.json.in` template file?

Background: The `*.in` file gets used to generate a `package-info.json` through some CMake scripting, so you might not have a `package-info.json` unless you've already compiled some code. I'm wondering whether the 1.0.0 I see in the screenshot is just the default value.

**Comment by byulparan** [comment]
It seems just default value. This is my `package-info.json.in` 

```json
{
	"author" : "Cycling '74",
	"description" : "Lightweight reference implementation of a package built using the Min-API.",
	"homepatcher" : "C++ Object Development Kit.maxpat",
	"max_version_min" : "8.0", "max_version_max" : "none",
	"name" : "@C74_PACKAGE_NAME@",
	"os" : {
		"macintosh" : {
			"platform" : [ "x64", "aarch64" ],
			"min_version" : "none"
		},
		"windows" : {
			"platform" : [ "x64" ],
			"min_version" : "none"
		}
	},
	"package_extra" : {
		"reverse_domain" : "com.cycling74",
		"copyright" : "Copyright (c) 2018 Cycling '74"
	},
	"tags" : [ ],
	"version" : "@GIT_VERSION_MAJ@.@GIT_VERSION_MIN@.@GIT_VERSION_SUB@",
	"website" : "http://www.github.com/Cycling74/min-devkit"
}
```
and `package-info.json`

```json
{
	"author" : "Cycling '74",
	"description" : "Lightweight reference implementation of a package built using the Min-API.",
	"homepatcher" : "C++ Object Development Kit.maxpat",
	"max_version_min" : "8.0", "max_version_max" : "none",
	"name" : "min-devkit",
	"os" : {
		"macintosh" : {
			"platform" : [ "x64", "aarch64" ],
			"min_version" : "none"
		},
		"windows" : {
			"platform" : [ "x64" ],
			"min_version" : "none"
		}
	},
	"package_extra" : {
		"reverse_domain" : "com.cycling74",
		"copyright" : "Copyright (c) 2018 Cycling '74"
	},
	"tags" : [ ],
	"version" : "1.0.0",
	"website" : "http://www.github.com/Cycling74/min-devkit"
}
```

**Comment by isabelgk** [comment]
Thanks for the info! 

After coming back to this, I realize that the general solution to this problem is to simply rename your local copy of the min-devkit.

It does seem contradictory for someone to clone the min-devkit in the Max Packages directory and then see this particular error in the Package Manager, so we can make a note of the request on the Package Manager side. However, I believe the solution of renaming your local copy is your best bet for resolving the current issue right away.

I hope that helps!

**Comment by byulparan** [comment]
I changed name 
1. directory name in max packages directory
2. name value in `package-info.json` 

Yeah~ I solved problem :-)  Thankyou.
