### ISSUE TITLE
min.*: cannot be loaded due to system security policy on Apple Silicon

### ISSUE THREAD

**Issue by caillonantoine** [Cycling74/min-devkit#200]
Building the min externals on a MacBook Pro (13-inch, M1, 2020) works ok, but loading any of them in max results in the following error:

![image](https://user-images.githubusercontent.com/32771520/149188798-2524d63a-0a8d-4073-b4f3-a967351db824.png)

I've tried several workarounds, including [this one](https://cycling74.com/articles/using-unsigned-max-externals-on-mac-os-10-15-catalina), without success.

**Comment by isabelgk** [comment]
Hi, thanks for the report! I can reproduce this. We'll look into it.

**Comment by isabelgk** [comment]
Hi @caillonantoine !

What is the output of the following?
```
lipo -info `which cmake`
```

**Comment by caillonantoine** [comment]
It does work ! Should I consider this method the "way to go" or will there be an official workaround ? Thanks again !

**Comment by jeremybernstein** [comment]
We may add something to the cmake process, but this is an Apple change, not a Max change, and users of our SDKs will need to keep apprised of changes to the Apple ecosystem and adapt accordingly. We'll help where we can, of course.
