### ISSUE TITLE
Adding new messages doesn't seem to work for UI controls

### ISSUE THREAD

**Issue by yeswecan** [Cycling74/min-devkit#217]
**Before filing a report**

I'm on the latest version of min-devkit, I made sure to pull and rebuild everything.

**Describe the bug**

I tried adding a new message to a number of classes and it only happens to work with non-ui objects.

**To Reproduce**

Add this message to the external object:
```
    message<> something { this, "something",
        MIN_FUNCTION {
            cout << "something was called!";
            return {};
        }
    };
```

Try to send `something` to the object. You will see the message posted only if it was not UI object.

**Expected behavior**

UI objects are expected to work just as non-UI ones, I suppose?

**OS:**

OSX 14.2.1

**Additional context**

Max 8.5.6

**Comment by isabelgk** [comment]
Hi @yeswecan ,

If you use something other than `cout << "foo"`, does it still not behave as expected? I could reproduce not getting a post from the UI object, but I could stop on a breakpoint in the function and do other things as expected (like an `output.send()` to an outlet).
