### ISSUE TITLE
min.jit.clamp example duplicating requires #include modification

### ISSUE THREAD

**Issue by gluon** [Cycling74/min-devkit#69]
Wanted to start by using min.jit.clamp as the base of my test
But there is an hardcoded inclusion in the test file.
>  #include "min.jit.clamp.cpp"

It gives this:
> /Users/julien/DATA/ME/DEV/MaxDevKit/min-devkit/source/projects/min.jit.crackSystem/min.jit.crackSystem_test.cpp:6:10: fatal error: 
>       'min.jit.clamp.cpp' file not found
> #include "**min.jit.clamp.cpp**"    // need the source of our object so that we can access it
>          ^
> 1 error generated.
> 
> ** BUILD FAILED **

Maybe we can add this to the documentation : modify the source file for a unit test (e.g. hello-world_test.cpp)

**Comment by tap** [comment]
The PM workflow does this automatically, but the pro workflow does still need it so it is now documented as recommended in this ticket.

Thanks!
