### ISSUE TITLE
request for better debug support, see API on call stack, perhaps PDB files for Windows

### ISSUE THREAD

**Issue by diablodale** [Cycling74/min-devkit#91]
My request is better debug support from the core Max api to enable API call tracing in debuggers. Specifically, to be able to see the cascade of API calls on the call stack.

One approach on the Windows platform might be to distribute PDB or stripped-PDB files with the libraries. Windows SDKs themselves have long done this. Yes, you support different platforms/compilers/debuggers. Easy-breezy. Automate the build with CI and it will deliver to you debug things for every box in your supported matrix. Distribution tools like NuGet are ready to manage such debug files. With the manual library install method, provide the debug files in separate labeled directories alongside the .lib's and doc it.

Attached is a screenshot of an exception I recently had. Nothing useful on the call stack. Nothing useful in the debug output. The only thing I had to go on was VS itself told me the exception type (access violation) and that it was trying to read 0x0032. That suggested to me the error was related to an offset of 32 rather than something reading 32 directly. I had little idea the sequence of events before the exception. No UI was rendered yet. I didn't know if I made a call that led to this or if this was in Max's code.

I isolated the problem with what you might describe as a binary-search-with-text-debug-output-markers. The bug was mine; how I had created my class hierarchy and how that interacted with the C++ runtime and Max. Much time/effort would have been saved if I saw in the call stack:

Helpful 😊 `class_new()` or `object_alloc()` or `max_jit_obex_new()`
Not helpful 😕`Max.exe!0000000001406ed859()`

![crash](https://user-images.githubusercontent.com/679350/32145827-edc89468-bcce-11e7-8285-f5c52022ab6a.png)

**Comment by tap** [comment]
Max symbols being unavailable is a topic related to Max itself rather than the Min API for accessing Max. Problems in this domain are best directed to support@cycling74.com.
